import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastHost } from "@/components/ToastHost";
import "./globals.css";

const genova = localFont({
  variable: "--font-genova",
  src: [
    { path: "../assets/fonts/Genova-Thin.otf", weight: "100" },
    { path: "../assets/fonts/Genova-Medium.otf", weight: "500" },
    { path: "../assets/fonts/Genova.otf", weight: "600" },
    { path: "../assets/fonts/Genova-Black.otf", weight: "900" },
    {
      path: "../assets/fonts/Genova-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../assets/fonts/Genova-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../assets/fonts/Genova-ThinItalic.otf",
      weight: "100",
      style: "italic",
    },
    {
      path: "../assets/fonts/Genova-BlackItalic.otf",
      weight: "900",
      style: "italic",
    },
  ],
});

const manifest = localFont({
  variable: "--font-manifest",
  src: "../assets/fonts/Mafinest-free.otf",
});

export const metadata: Metadata = {
  title: "Elevate Heart Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${genova.variable} ${manifest.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <ToastHost />
      </body>
    </html>
  );
}
